package org.akhikhl.examples.gretty.hellogretty

import geb.spock.GebReportingSpec

class RequestResponseIT extends GebReportingSpec {

  private static String host
  private static int port
  private static String contextPath

  void setupSpec() {
    host = System.getProperty('gretty.host')
    port = System.getProperty('gretty.port') as int
    contextPath = System.getProperty('contextPath')
  }
  
  def 'should get expected static page'() {
  when:
    go "http://${host}:${port}/abc/index.html"
  then:
    // contextPath is overridden in jetty-env.xml
    contextPath != '/abc'
    $('h1').text() == 'Hello, world!'
    $('p', 0).text() == /This is static HTML page./
    $('p strong').text() == /Please note different context path: it was set in "jetty-env.xml"./
  }

  def 'should get expected response from servlet'() {
  when:
    go "http://${host}:${port}/abc/dynamic"
  then:
    // contextPath is overridden in jetty-env.xml
    contextPath != '/abc'
    $('h1').text() == 'Hello, world!'
    $('p', 0).text() == /This is dynamic HTML page generated by servlet./
    $('p strong').text() == /Please note different context path: it was set in "jetty-env.xml"./
  }
}
