package hellogretty

import geb.spock.GebReportingSpec

class RequestResponseIT extends GebReportingSpec {

  def 'should get expected response from servlet'() {
  when:
    go 'http://localhost:8080/helloGretty7/hello'
  then:
    $('h1').text() == 'Dynamic content generated by servlet'
    $('p', 0).text() == /Hello there! It's fine weather, isn't it?/
  }

  def 'should get expected static page'() {
  when:
    go 'http://localhost:8080/helloGretty7/index.html'
  then:
    $('h1').text() == 'Hello, world!'
  }
}
