package hellogretty;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.configuration.ConfigurationException;
import org.apache.commons.configuration.PropertiesConfiguration;

public class ExampleServlet extends HttpServlet {

  private static final long serialVersionUID = -6506276378398106663L;

  @Override
  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    PropertiesConfiguration config;
    try {
      config = new PropertiesConfiguration();
      config.load(this.getClass().getClassLoader().getResource("hellogretty/messages.properties"));
    } catch (ConfigurationException ex) {
      throw new ServletException(ex);
    }
    String greeting = config.getString("greeting");
    try (PrintWriter out = response.getWriter()) {
      out.println("<html><body><h1>" + greeting + "</h1>");
      out.println("<div>Today is " + new Date() + ".</div>");
      out.println("<div>The weather is fine, isn't it?</div>");
      out.println("<div>This is dynamic content generated by servlet.</div>");
      out.println("</body></html>");
      out.println();
      out.flush();
    }
  }
}
