package hellogretty

import geb.spock.GebReportingSpec
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class RequestResponseIT extends GebReportingSpec {

  private static final Logger log = LoggerFactory.getLogger(RequestResponseIT)

  private static String baseURI

  void setupSpec() {
    baseURI = System.getProperty('gretty.baseURI')
  }

  def 'should get expected static page'() {
  when:
    go "${baseURI}/index.html"
  then:
    $('h1').text() == 'Hello, world!'
    $('p', 0).text() == /This is static HTML page./
  }

  def 'should get expected response from servlet'() {
  when:
    go "${baseURI}/dynamic"
  then:
    $('h1').text() == 'Hello, world!'
    $('p', 0).text() == /This is dynamic HTML page generated by servlet./
  }
}
